baseURL = "https://announcements.enchantedcode.co.uk/"
languageCode = 'en'
title = 'Announcements By Enchanted Code'
theme = ["github.com/hanwenguo/hugo-theme-nostyleplease"]
enableGitInfo = true
paginate = 6

[permalinks]
posts = "/posts/:slug/"
