[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scripts"
requires-python = ">=3.11"
dependencies = [
    "feedparser~=6.0.11"
]
version = "0.0.0"

[tool.hatch.envs.default.scripts]
injest = "python scripts/injest-blog-posts.py"
